# Generated by Django 5.2.1 on 2025-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('f_name', models.CharField(default='None', max_length=50, verbose_name='First Name')),
                ('m_name', models.CharField(default='None', max_length=50, verbose_name='Middle Name')),
                ('stud_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Student ID')),
                ('profile', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('section', models.CharField(default='None', max_length=3)),
            ],
        ),
    ]
