# Generated by Django 5.2.1 on 2025-05-11 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='F_Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='M_Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Profile',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
