# Generated by Django 5.2.1 on 2025-05-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_physics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Physics',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
