# Generated by Django 5.2.1 on 2025-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('F_Name', models.CharField(default='None', max_length=50)),
                ('M_Name', models.CharField(default='None', max_length=50)),
                ('stud_Id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Profile', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
