# Generated by Django 5.2.1 on 2025-05-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='F_name',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
