# Generated by Django 5.2.1 on 2025-05-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_mark_f_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='F_name',
        ),
    ]
