# Generated by Django 5.2.1 on 2025-05-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biology',
            field=models.IntegerField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='geography',
            field=models.IntegerField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='physics',
            field=models.IntegerField(default='0', max_length=3),
        ),
    ]
